app:
  restart: always
  build: .
  dockerfile: Dockerfile.app
  command: ./braise/run_app.sh
  ports:
    - "80:5000"
worker:
  restart: always
  build: .
  dockerfile: Dockerfile.app
  command: ./braise/run_worker.sh
